package com.diasmart.springapi.users.entity;

import com.diasmart.springapi.shared.enums.AccountStatus;
import com.diasmart.springapi.shared.enums.UserRole;
import jakarta.persistence.*;

import java.time.Instant;

/**
 * AppUser represents a user account in the Dia-Smart backend.
 *
 * This entity maps to the app_users table.
 *
 * Users can be:
 * - PATIENT
 * - CAREGIVER
 * - DOCTOR
 * - ADMIN
 *
 * Important:
 * We store passwordHash, not the raw password.
 */
@Entity
@Table(name = "app_users", uniqueConstraints = {
        @UniqueConstraint(name = "uk_app_users_email", columnNames = "email")
})
public class AppUser {

    /**
     * Primary key.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User's full name.
     */
    @Column(name = "full_name", nullable = false, length = 150)
    private String fullName;

    /**
     * User email.
     * This must be unique because it is used for login.
     */
    @Column(name = "email", nullable = false, unique = true, length = 180)
    private String email;

    /**
     * Encrypted password.
     * Never store the raw password.
     */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    /**
     * Role used for RBAC authorization.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 30)
    private UserRole role;

    /**
     * Account status controls whether the user can log in.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "account_status", nullable = false, length = 30)
    private AccountStatus accountStatus;

    /**
     * Optional phone/contact number.
     */
    @Column(name = "phone_number", length = 30)
    private String phoneNumber;

    /**
     * Record creation timestamp.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Last update timestamp.
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    public AppUser() {
    }

    public AppUser(
            String fullName,
            String email,
            String passwordHash,
            UserRole role,
            AccountStatus accountStatus) {
        this.fullName = fullName;
        this.email = email;
        this.passwordHash = passwordHash;
        this.role = role;
        this.accountStatus = accountStatus;
    }

    /**
     * Runs automatically before first database insert.
     */
    @PrePersist
    public void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;

        if (this.accountStatus == null) {
            this.accountStatus = AccountStatus.ACTIVE;
        }
    }

    /**
     * Runs automatically before database update.
     */
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = Instant.now();
    }

    public Long getId() {
        return id;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getEmail() {
        return email;
    }

    /**
     * Store email in lowercase to avoid duplicate login issues.
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim().toLowerCase();
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public UserRole getRole() {
        return role;
    }

    public void setRole(UserRole role) {
        this.role = role;
    }

    public AccountStatus getAccountStatus() {
        return accountStatus;
    }

    public void setAccountStatus(AccountStatus accountStatus) {
        this.accountStatus = accountStatus;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}