server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    open-in-view: false

mqtt:
  broker:
    ssl: ${MQTT_BROKER}

  client:
    id: diasmart-backend

  topic: ${MQTT_TOPIC}