server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diasmart
    username: postgres
    password: Arnikan18
    driver-class-name: org.postgresql.Driver

    jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

logging:
  level:
    "[org.springframework.security]": INFO
    "[org.hibernate.SQL]": DEBUG

app:
  jwt:
    secret: ${JWT_SECRET:}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}

mqtt:
  broker:
    ssl: ${MQTT_BROKER}

  client:
    id: diasmart-backend-dev

  topic: ${MQTT_TOPIC}