#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CONFIG_FILE = path.join(__dirname, 'diasmart.config.js');

if (!fs.existsSync(CONFIG_FILE)) {
  console.error('[CONFIG ERROR] Missing config/diasmart.config.js');
  console.error('');
  console.error('Create it using:');
  console.error('  copy config\\diasmart.config.example.js config\\diasmart.config.js');
  console.error('');
  console.error('Then edit config/diasmart.config.js with your local Wi-Fi, database, and backend values.');
  process.exit(1);
}

const cfg = require(CONFIG_FILE);

const {
  network,
  wifi,
  postgres,
  server,
  mqtt,
  sensors,
  glucometer,
  dosageBle,
  paths
} = cfg;

function writeFile(relPath, content) {
  const abs = path.join(ROOT, relPath);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content, 'utf8');
  console.log(`[OK] ${relPath}`);
}

function toCppFloatLiteral(value, fallback = '1.0f') {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) {
    return fallback;
  }
  if (Number.isInteger(numeric)) {
    return `${numeric}.0f`;
  }
  return `${numeric}f`;
}

const loadCellCalibrationLiteral = toCppFloatLiteral(sensors.loadCellCalibration, '245.0f');

const backendEnv = `# Auto-generated by config/apply-config.js
# This file is generated from config/diasmart.config.js.
# Do not commit this file.
PGHOST=${postgres.host}
PGPORT=${postgres.port}
PGDATABASE=${postgres.database}
PGUSER=${postgres.user}
PGPASSWORD=${postgres.password}
PORT=${server.port}
GLUCO_FILE_ONLY=${server.fileOnlyMode ? '1' : ''}
CORS_ORIGIN=${server.corsOrigin}
MQTT_ENABLED=${mqtt.enabled ? '1' : ''}
MQTT_BROKER_URL=${mqtt.brokerUrl}
MQTT_USERNAME=${mqtt.username}
MQTT_PASSWORD=${mqtt.password}
MQTT_CLIENT_ID=${mqtt.clientId}
MQTT_TOPIC_PREFIX=${mqtt.topicPrefix}
`;

const firmwareHeader = `#pragma once

#define WIFI_SSID \"${wifi.ssid}\"
#define WIFI_PASSWORD \"${wifi.password}\"
#define BACKEND_IP \"${network.backendIp}\"
#define BACKEND_PORT ${network.backendPort}
#define BACKEND_READINGS_URL \"http://${network.backendIp}:${network.backendPort}/api/readings\"
#define BACKEND_GLUCO_BATCH_URL \"http://${network.backendIp}:${network.backendPort}/api/glucometer/batch\"
#define BACKEND_GLUCO_SINGLE_URL \"http://${network.backendIp}:${network.backendPort}/api/glucometer\"
#define BACKEND_DOSAGE_URL \"http://${network.backendIp}:${network.backendPort}/api/dosage\"
#define ESPNOW_CHANNEL ${network.espNowChannel}
#define TEMP_SENSOR_PIN ${sensors.tempSensorPin}
#define DOOR_SENSOR_PIN ${sensors.doorSensorPin}
#define HX711_DOUT_PIN ${sensors.hx711DoutPin}
#define HX711_CLK_PIN ${sensors.hx711ClkPin}
#define LOAD_CELL_CALIBRATION ${loadCellCalibrationLiteral}
#define GLUCO_BLE_PIN \"${glucometer.blePin}\"
#define GLUCO_DEVICE_NAME \"${glucometer.deviceName}\"
#define GLUCO_MAX_BUFFER_RECORDS ${glucometer.maxBufferRecords}
#define GLUCO_BATCH_SIZE ${glucometer.batchSize}
#define DOSAGE_BLE_DEVICE_NAME \"${dosageBle.deviceName}\"
#define DOSAGE_BLE_SERVICE_UUID \"${dosageBle.serviceUuid}\"
#define DOSAGE_BLE_CHARACTERISTIC_UUID \"${dosageBle.characteristicUuid}\"
`;

const appConfig = `export const AppConfig = {
  apiBaseUrl: 'http://${network.backendIp}:${network.backendPort}',
  backendIp: '${network.backendIp}',
  backendPort: ${network.backendPort},
} as const;

export default AppConfig;
`;

writeFile(paths.backendEnv, backendEnv);
writeFile(paths.firmwareHeader, firmwareHeader);
writeFile(paths.appConfig, appConfig);
