; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
; update upload_port to the correct COM port when hardware is connected
upload_port = COM8

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.9.0
    bogde/HX711 @ ^0.7.5

build_flags =
    -DCORE_DEBUG_LEVEL=0
